name: Zoya Auto-Provision

on:
  workflow_dispatch:

jobs:
  run-zoya:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout Repo
      uses: actions/checkout@v3

    - name: Setup Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install OCI Library
      run: pip install oci

    - name: Setup OCI Config & Key
      run: |
        mkdir -p ~/.oci
        cat <<EOF > ~/.oci/config
        [DEFAULT]
        user=ocid1.user.oc1..aaaaaaaavhodc4li4cbn465epajsmlhrqlgnl5bhzek2p3ruotuuqfqsk2qq
        fingerprint=1b:50:d2:34:b2:c1:05:05:6c:47:4f:3a:66:e6:bd:55
        tenancy=ocid1.tenancy.oc1..aaaaaaaajpyefe3wmwguew5lipebb66etskt4tilonv4opiapcg6lwtn6opa
        region=ap-mumbai-1
        key_file=~/.oci/key.pem
        EOF
        echo "${{ secrets.OCI_KEY }}" > ~/.oci/key.pem
        chmod 600 ~/.oci/key.pem

    - name: Run Zoya Script
      run: python -u zoya.py
      
